---

- name: Install Python Pip
  become: yes
  apt:
    name: python-pip
    state: present

- name: Install Supervisor via pip
  become: yes
  pip:
    name: supervisor
    state: present
    version: "{{ sansible_supervisor_version | default(omit) }}"

- name: Create /usr/bin symlinks to supervisorctl and supervisord usually created by packages
  become: yes
  file:
    dest: "/usr/bin/{{ item }}"
    src: "/usr/local/bin/{{ item }}"
    state: link
  with_items:
    - supervisorctl
    - supervisord

- name: Create required conf and log directories
  become: yes
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/supervisor
    - /etc/supervisor/conf.d/
    - /var/log/supervisor

- name: Add default Supervisor config
  become: yes
  copy:
    dest: /etc/supervisor/supervisord.conf
    mode: u+rw,g+r,o+r
    src: supervisord.conf

- name: Add SysVinit script
  become: yes
  copy:
    dest: /etc/init.d/supervisor
    mode: u+rwx,g+rw,o+x
    src: service.sysvinit
  when: ansible_service_mgr != "systemd"

- name: Add SystemD script
  become: yes
  template:
    dest: /etc/systemd/system/supervisor.service
    mode: u+rw,g+rw,o+r
    src: service.systemd.j2
  when: ansible_service_mgr == "systemd"

- name: Ensure Supervisor is enabled for SysV
  become: yes
  service:
    name: supervisor
    enabled: yes
  when:
    - sansible_supervisor_start_on_boot
    - ansible_service_mgr != "systemd"

- name: Ensure Supervisor is enabled for SystemD
  become: yes
  systemd:
    daemon_reload: yes
    name: supervisor
    enabled: yes
  when:
    - sansible_supervisor_start_on_boot
    - ansible_service_mgr == "systemd"
