---

- name: Configure Supervisor settings
  become: yes
  ini_file:
    dest: "{{ sansible_supervisor_conf_settings_file }}"
    mode: 0644
    option: "{{ item.name }}"
    section: "{{ item.section }}"
    value: "{{ item.value }}"
  when: sansible_supervisor_conf_settings | length > 0
  with_items: "{{ sansible_supervisor_conf_settings }}"
  notify:
    - restart supervisor

- name: Ensure supervisor service is started
  become: yes
  service:
    name: supervisor
    state: started
